### ISSUE TITLE
unsafe work with the file.

### ISSUE THREAD

**Issue by ihsinme** [JLouhela/todomo#1]
Good afternoon.
you are working with a writeable file with a predictable name and without setting restrictive access rights.
this can lead to security, disclosure and accessibility issues.
I propose to consider the issue of limiting rights and forming a name, for example, through `mkstemp`

https://github.com/JLouhela/todomo/blob/137fca0798b2283eef43498f64472bc14916ccfc/src/todo_saver.c#L20

**Comment by JLouhela** [comment]
Thank you for the feedback! You caught me off-guard, I didn't really expect anyone to run across anything I have here in Github.

I will study the usage of mkstemp and gladly take the opportunity to learn something from others.

**Comment by JLouhela** [comment]
TMP file not used currently, therefore this finding is no longer valid.

I will likely need to file modifying functions in the future again and this tip will be useful then.
